package at.htl.mirrorhome.websocket

enum class WebSocketCommand {
    MIRROR_STATE_CHANGED,
    MOTION_DETECTED,
    USER_DETECTED,
    USER_DATA_FETCHED,
    USER_DATA_CHANGED,
    USER_LOGOUT,
    UNKNOWN_USER_DETECTED,
    SENSOR_SUMMARY_CHANGED,
    ACTUATOR_SUMMARY_CHANGED,
    THING_SUMMARY_CHANGED,
    DEMO_LIGHT_ON,
    DEMO_LIGHT_OFF
}