package at.htl.mirrorhome.user

enum class RegistrationState {
    WAITING_FOR_UNKNOWN_USER_EVENT,
    CONFIRM_DENY_REGISTRATION,
    STARTING_REGISTRATION_PROCESS,
    PROFILPIC_STORED,
    PROFILPIC_INVALID,
    QR_CODE_SCANNED,
    PROCESSING_REGISTRATION,
    USER_CREATED,
    REGISTRATION_ABORTED
}